java_binary(
    name = "RobotBuilder",
    main_class = "robotbuilder.RobotBuilder",
    visibility = ["//visibility:public"],
    runtime_deps = ["@bazelrio_edu_wpi_first_tools_robotbuilder//jar"],
)
