load("//dependencies/tools:tool_launchers.bzl", "java_tool_launcher")

java_tool_launcher(
    name = "OutlineViewer",
    base_repo_name = "bazelrio_edu_wpi_first_tools_outlineviewer",
    main_class = "edu.wpi.first.tools.outlineviewer.Main",
)
